export const types = {
    // Sync
    FILL_POSTS: 'FILL_POSTS',
    CREATE_POST: 'CREATE_POST',
    CLEAR_POSTS: 'CLEAR_POSTS',

    // Async
    FETCH_POST_ASYNC: 'FETCH_POST_ASYNC',
    CREATE_POST_ASYNC: 'CREATE_POST_ASYNC',
}